export const FILE_UPLOADS_MAX_NUMBER = Number(
  process.env.FILE_UPLOADS_MAX_NUMBER,
);

export const FILE_UPLOADS_PUBLIC_PATH = process.env.FILE_UPLOADS_PUBLIC_PATH;
export const FILE_UPLOADS_PRIVATE_PATH = process.env.FILE_UPLOADS_PRIVATE_PATH;

export const FOLDER_PUBLIC = process.env.FOLDER_PUBLIC;
export const FOLDER_PRIVATE = process.env.FOLDER_PRIVATE;

export const PATH_PRIVATE_FOLDER =
  FILE_UPLOADS_PRIVATE_PATH + '/' + FOLDER_PRIVATE;

export const PATH_PUBLIC_FOLDER =
  FILE_UPLOADS_PUBLIC_PATH + '/' + FOLDER_PUBLIC;
